# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('boats', models.ManyToManyField(related_name='bookings', to='boating.Boat')),
            ],
        ),
        migrations.CreateModel(
            name='HirePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, b'Monday'), (2, b'Tuesday'), (3, b'Wednesday'), (4, b'Thursday'), (5, b'Friday'), (6, b'Saturday'), (7, b'Sunday')], verbose_name=b'Day')),
                ('from_hour', models.TimeField(verbose_name=b'Opening')),
                ('to_hour', models.TimeField(verbose_name=b'Closing')),
                ('hire_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='boating.HirePoint')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hire_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boating.HirePoint'),
        ),
        migrations.AddField(
            model_name='boat',
            name='hire_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='boating.HirePoint'),
        ),
    ]
